# Generated by Django 5.1 on 2024-11-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('gerente', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.CharField(max_length=100)),
            ],
        ),
    ]
